version: "3.1"
services:
  app:
    build:
      context: ./docker/services/php
    volumes:
      - ./docker/services/php/php.ini:/usr/local/etc/php/conf.d/40-custom.ini
      - ./docker/logs:/var/www/storage/logs
      - ./testapp:/var/www
      - ./fastcrud:/var/fastcrud
    depends_on:
      - pgsql
      - redis

  webserver:
    image: nginx:alpine
    ports:
      - ${HTTP_PORT}:80
    volumes:
      - ./docker/services/nginx:/etc/nginx/conf.d
      - ./testapp:/var/www
      - ./fastcrud:/var/fastcrud
    depends_on:
      - app

  pgsql:
    image: postgres:10-alpine
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./docker/storage/pgsql:/var/lib/postgresql/data

  redis:
    image: redis:${REDIS_VERSION}
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ./docker/storage/redis:/data

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: ${DOCKER_SUBNET}
